globalThis.FlowArrow = globalThis.FlowArrow || {};
// Section 9 + section 3: CSS for the closed shadow root. Person A owns this file.
// Devanagari fallback required for Nepali captions.
globalThis.FlowArrow.styles = [
  ":host { all: initial; }",
  ".fa-launcher {",
  "  position: fixed; right: 20px; bottom: 20px; width: 56px; height: 56px;",
  "  border-radius: 50%; border: none; cursor: pointer; z-index: 2147483647;",
  "  background: #26235C; color: #FFD23F; font-size: 28px; line-height: 1;",
  "  box-shadow: 0 4px 16px rgba(0,0,0,0.35);",
  "}",
  ".fa-card {",
  "  position: fixed; right: 20px; bottom: 88px; width: 340px; z-index: 2147483647;",
  "  background: #26235C; color: #fff; border-radius: 14px; padding: 14px;",
  "  font-family: 'FlowArrow Atkinson Hyperlegible', 'Noto Sans Devanagari', system-ui, sans-serif;",
  "  box-shadow: 0 8px 28px rgba(0,0,0,0.4);",
  "}",
  ".fa-langrow { display: flex; gap: 8px; margin-bottom: 8px; }",
  ".fa-lang { flex: 1; padding: 6px; border-radius: 8px; border: 1px solid #555;",
  "  background: transparent; color: #fff; cursor: pointer; font-weight: 700; }",
  ".fa-lang[aria-pressed='true'] { background: #FFD23F; color: #26235C; border-color: #FFD23F; }",
  ".fa-goal { width: 100%; min-height: 64px; border-radius: 8px; padding: 8px;",
  "  font-size: 15px; box-sizing: border-box; }",
  ".fa-row { display: flex; gap: 8px; margin-top: 10px; align-items: center; }",
  ".fa-send { flex: 1; background: #FFD23F; color: #26235C; border: none;",
  "  border-radius: 8px; padding: 10px; font-weight: 800; cursor: pointer; }",
  ".fa-iconbtn { background: transparent; color: #fff; border: 1px solid #555;",
  "  border-radius: 8px; padding: 8px 10px; cursor: pointer; }",
  ".fa-pill {",
  "  position: fixed; right: 20px; bottom: 20px; width: 320px; z-index: 2147483647;",
  "  background: #26235C; color: #fff; border-radius: 999px; padding: 10px 14px;",
  "  font-family: 'FlowArrow Atkinson Hyperlegible', 'Noto Sans Devanagari', system-ui, sans-serif;",
  "}",
].join("\n");
